### ISSUE TITLE
bignum low_level_view.d assert failure on Windows

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#285] opened 2020-06-22 22:40 UTC
See error below. I get this when running `dub test` after commenting out the other static assert that was causing problems.
```
C:\Users\[removed]\Documents\GitHub\mir-algorithm>dub test
Generating test runner configuration 'mir-algorithm-test-default' for 'default' (library).
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Performing "unittest" build using dmd for x86_64.
mir-core 1.1.7: target for configuration "library" is up to date.
mir-algorithm 3.9.0+commit.4.gb78e39d: building configuration "mir-algorithm-test-default"...
Warning: multivariate cubic spline with derivatives was not tested!!!
Warning: multivariate cubic spline with derivatives was not tested!!!
Linking...
LINK : .dub\build\mir-algorithm-test-default-unittest-windows-x86_64-dmd_2092-B362FAEFBFEC7AA6D1882178E33451B4\mir-algorithm-test-default.exe not found or not built by the last incremental link; performing full link
   Creating library .dub\build\mir-algorithm-test-default-unittest-windows-x86_64-dmd_2092-B362FAEFBFEC7AA6D1882178E33451B4\mir-algorithm-test-default.lib and object .dub\build\mir-algorithm-test-default-unittest-windows-x86_64-dmd_2092-B362FAEFBFEC7AA6D1882178E33451B4\mir-algorithm-test-default.exp
To force a rebuild of up-to-date targets, run again with --force.
Running .\mir-algorithm-test-default.exe
source\mir\bignum\low_level_view.d(1877): [unittest] unittest failure

core.exception.AssertError@source\mir\bignum\low_level_view.d(1877): unittest failure
----------------
0x00007FF6E31AD632 in d_unittestp
0x00007FF6E2AC8FA4 in mir.bignum.low_level_view.__unittest_L1850_C1 at C:\Users\[removed]Documents\GitHub\mir-algorithm\source\mir\bignum\low_level_view.d(1877)
0x00007FF6E2B24A8E in void mir.bignum.low_level_view.__modtest()
0x00007FF6E31D5EE9 in int core.runtime.runModuleUnitTests().__foreachbody1(object.ModuleInfo*)
0x00007FF6E31C55F7 in int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)).__lambda2(immutable(object.ModuleInfo*))
0x00007FF6E31DCB44 in int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))).__foreachbody2(ref rt.sections_win64.SectionGroup)
0x00007FF6E31DCAAF in int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*)))
0x00007FF6E31C55B7 in int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*))
0x00007FF6E31D5D1E in runModuleUnitTests
0x00007FF6E31BFCA5 in void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll()
0x00007FF6E31BFC0C in void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).tryExec(scope void delegate())
0x00007FF6E31BFA43 in d_run_main2
0x00007FF6E31A3990 in d_run_main
0x00007FF6E28E9782 in dub_test_root._d_cmain!().main at C:\D\dmd2\windows\bin64\..\..\src\druntime\import\core\internal\entrypoint.d(29)
0x00007FF6E3297AC4 in __scrt_common_main_seh at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288)
0x00007FFD2D9A6FD4 in BaseThreadInitThunk
0x00007FFD2DADCEC1 in RtlUserThreadStart
1/54 unittests FAILED
Program exited with code 1
```

**Comment by 9il** [comment] 2020-06-23 01:20
Duplicate of #282 .It is a DMD bug, not Mir.

**Comment by jmh530** [comment] 2020-06-24 23:46
Most recent attempt:

```
C:\Users\[removed]\Documents\GitHub\mir-algorithm>dub test --arch=x86_64 --compiler=dmd
Generating test runner configuration 'mir-algorithm-test-default' for 'default' (library).
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Performing "unittest" build using dmd for x86_64.
mir-core 1.1.7: building configuration "library"...
mir-algorithm 3.9.1: building configuration "mir-algorithm-test-default"...
Warning: multivariate cubic spline with derivatives was not tested!!!
Warning: multivariate cubic spline with derivatives was not tested!!!
Linking...
   Creating library .dub\build\mir-algorithm-test-default-unittest-windows-x86_64-dmd_2092-BEBEBE9BD2CEA71D0CAFA8B56CB88FC0\mir-algorithm-test-default.lib and object .dub\build\mir-algorithm-test-default-unittest-windows-x86_64-dmd_2092-BEBEBE9BD2CEA71D0CAFA8B56CB88FC0\mir-algorithm-test-default.exp
Running .\mir-algorithm-test-default.exe
source\mir\bignum\low_level_view.d(1964): [unittest] unittest failure

core.exception.AssertError@source\mir\bignum\low_level_view.d(1964): unittest failure
----------------
0x00007FF7B674F542 in d_unittestp
0x00007FF7B6020ADE in mir.bignum.low_level_view.__unittest_L1867_C1 at C:\Users\[removed]\Documents\GitHub\mir-algorithm\source\mir\bignum\low_level_view.d(1964)
0x00007FF7B607BBBE in void mir.bignum.low_level_view.__modtest()
0x00007FF7B6777E39 in int core.runtime.runModuleUnitTests().__foreachbody1(object.ModuleInfo*)
0x00007FF7B6767517 in int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)).__lambda2(immutable(object.ModuleInfo*))
0x00007FF7B677EA64 in int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))).__foreachbody2(ref rt.sections_win64.SectionGroup)
0x00007FF7B677E9CF in int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*)))
0x00007FF7B67674D7 in int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*))
0x00007FF7B6777C6E in runModuleUnitTests
0x00007FF7B6761BB5 in void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll()
0x00007FF7B6761B1C in void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).tryExec(scope void delegate())
0x00007FF7B6761953 in d_run_main2
0x00007FF7B67458A0 in d_run_main
0x00007FF7B5E3A7F2 in dub_test_root._d_cmain!().main at C:\D\dmd2\windows\bin64\..\..\src\druntime\import\core\internal\entrypoint.d(29)
0x00007FF7B683A94D in __scrt_common_main_seh at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl(259)
0x00007FFE546F7BD4 in BaseThreadInitThunk
0x00007FFE5662CE51 in RtlUserThreadStart
1/54 unittests FAILED
Program exited with code 1
```

**Comment by 9il** [comment] 2020-06-25 00:20
thanks, hopefully, this is the final fix

**Comment by jmh530** [comment] 2020-06-25 00:32
You might need one more...the error above was for line 1964, but there was no change to it. I'm still getting the same assert error on that line. However, if I comment out that line, then `dub test` as above compiles without error.

**Comment by jmh530** [comment] 2020-06-25 10:42
Passed without error.

**Closed** 2020-06-25 11:46 UTC
